PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE users (id integer primary key autoincrement not null, username text unique, fio text,studnum text, photo blob);
CREATE TABLE queue (id integer primary key autoincrement not null, username text not null, password text not null, date datetime not null default current_timestamp, done boolean not null default 'false',resetedby text);
CREATE TABLE quota (id integer primary key autoincrement not null, username text not null unique, usedspace integer not null, softlimit integer not null);
CREATE UNIQUE INDEX quota_idx on quota (username);
CREATE UNIQUE INDEX users_idx on users (username);
CREATE INDEX users_idx_fio on users (fio);
CREATE INDEX users_idx_studnum on users (studnum);
COMMIT;
